name: example
description: How to use RotatedCornerDecoration
publish_to: none

version: 2.0.0

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  rotated_corner_decoration:
    path: ..
